version: "3"
services:
  banner-rotation:
    image: banner-rotation:develop
    ports:
      - "8888:8888"
    networks:
      docker:
        ipv4_address: 10.5.0.2

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "banner_rotation"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      docker:
        ipv4_address: 10.5.0.3

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      docker:
        ipv4_address: 10.5.0.4

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.5.0.5
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      docker:
        ipv4_address: 10.5.0.5

networks:
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1