httpserver:
  host:
  port: 8889
db:
  dsn: postgres://user:password@127.0.0.1:5432/banner_rotation
  maxConnectAttempts: 5
kafka:
  topic: events
  brokerAddress: 127.0.0.1:9092
  maxConnectAttempts: 5